### ISSUE TITLE
Replace scoped verbs with across()

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/course-site#217]
See `dplyr` 1.0.0 and the [colwise operations vignette](https://dplyr.tidyverse.org/dev/articles/colwise.html)

**Comment by djanvier** [comment]
I hope you don't mind, I had a few questions before I got started:
- Do I keep the info about the variants just in case students are working with older versions of R and R Studio and can’t update to the latest version of dplyr?
- Should I include `c_across()`?
- Since a lot of the examples in the lesson focused on the “most useful” variants, should I come up with new examples or solely replace the examples that are already there with the `across()` function?
- Should I explain how the variants are replaced or just focus on `across()` by itself?

**Comment by bensoltoff** [comment]
Good questions!

- No, that would probably be too confusing. At this point we assume students have the most recent version. Perhaps just add a note saying you need at least version X.X.X of `dplyr` to access these functions
- `c_across()` is probably a bit advanced for this class
- Primarily aim to replace the existing examples, but you don't have to literally translate them to the new syntax. When I first added that in I basically cribbed from the documentation in `dplyr`. I would suggest using the column-wise operations vignette as a starting point, but try to adapt some of those examples using data we have in the `rcfss` package - that is, things they have seen (or will see later) in other examples in the class. One of my overarching goals for the class is to replace all the standard canned data set examples (e.g. diamonds, mtcars) with social science datasets curated in `rcfss`.
- Just focus on `across()` - we'll basically treat the `_if()`, `at_()`, and `_all()` suffixes as if they don't exist

**Comment by djanvier** [comment]
Great, thank you!

**Comment by djanvier** [comment]
Hello there! I finished this task, but I'm a little confused about what to stage for my final commit. The following changes are in my Git tab:
![image](https://user-images.githubusercontent.com/52148607/96678143-b291e680-1336-11eb-872d-5b8e6f862b11.png)
You'll also notice I changed the file extension from `.Rmarkdown` to `.Rmd` in order to knit the document
