### ISSUE TITLE
Update Modelling Tutorials to Use `tidymodels` Framework 

### ISSUE THREAD

**Issue by deblnia** [uc-cfss/course-site#254]
Not sure how you feel about this -- definitely a difficult change to make, presumes some stat background, and probably goes along the lines of updating to encompass more of dplyr 1.0 -- but I've found the pre-processing framework fairly lovely, the [documentation](https://www.tidymodels.org/) is good, and there are a [few](https://juliasilge.com/blog/xgboost-tune-volleyball/) [nice](https://nyhackr.blob.core.windows.net/presentations/Totally_Tidy_Tuning_Tools-Max_Kuhn.pdf) [tutorials](http://www.rebeccabarter.com/blog/2020-03-25_machine_learning/#put-it-all-together-in-a-workflow) out there. 

Talk soon 😄

**Comment by bensoltoff** [comment]
Definitely in my thoughts (see #230). I'm trying to re-envision the whole stat learning module. It covers two days and I presume no prior math background, so I have to start from square one essentially. I got rid of cross-validation and tree-based models because most students didn't seem to really understand how they worked (so much copy and pasting from the lecture notes). But I really like the `tidymodels` interface and I think it will be very useful for modelers moving forward.

That said, I'm not entirely comfortable shifting to it entirely. I still think students need to understand how to call some of the core model functions like `lm()` and interact with those objects.

**Comment by deblnia** [comment]
Closing to avoid redundancy!
